### ISSUE TITLE
Unable to Delete Users with a 500 Server Response Error

### ISSUE THREAD

**Issue by bedwardly-down** [fr0tt/benotes#16]
## Steps to Reproduce ##
* Login
* Create a test user with a fake email account as admin account
* Navigate to Users page
* Select test user
* Select Delete
* Creating any notes doesn't matter here

## Expected Results ##
* User is deleted along with their content

## Current Results ##
![copy](https://user-images.githubusercontent.com/59133880/123546264-7d3d6400-d721-11eb-892d-35c40290a780.png)

**Comment by fr0tt** [comment]
Thank you for finding another bug and telling me about it !

I fixed the error message and the problem itself. 

(Ironically "Creating any notes doesn't matter here" is actually not really the truth. It's actually the problem itself because so far I have only tested deleting users without them having any posts but that changed recently by creating three example posts automatically per user.)

**Comment by bedwardly-down** [comment]
Oh, I didn’t know that last part. When I said they didn’t matter, I was meaning I hadn’t created anything with the user. Haha. I’m at work but can test after I get off if you pushed an update.

**Comment by bedwardly-down** [comment]
Updated with latest commit and it fixed the issue. Thanks. :D

**Comment by fr0tt** [comment]
You're very welcome ;)
