### ISSUE TITLE
Blank page after installation

### ISSUE THREAD

**Issue by EmanDS** [fr0tt/benotes#37]
Hello, once installed I get a blank page.

Any idea how to solve it?

Thanks

**Comment by fr0tt** [comment]
Hi,

did you follow one of the [installation guides](https://github.com/fr0tt/benotes/blob/master/installation.md) ?

How/where did you install it (e.g. local, Heroku, Docker, docker-compose, ...) ?

**Comment by EmanDS** [comment]
Hi,

Thanks for your answer.
I tried Classic and Docker.

Perhaps I did something wrong ?

**Comment by fr0tt** [comment]
This week I'm currently not able to test it out myself because I have no computer with me, but it think it should work.

So let's try the classical method:
One more question, which operation system are you using and which webserver ?

Usually if something doesn't work the best bet is to have a look at the logs. 
So try to check if your webserver's logs (depending on your system it could be stored in /var/log/apache2/error.log or /var/log/nginx/error.log or something similar) contain anything useful that you could tell/write me. 
Otherwise check if the application's log contains anything, stored in .../storage/logs/lumen-2022-08-11.log

**Comment by EmanDS** [comment]
Thanks, I had a look to the logs but could not find anything.
I am going to install it again and see

**Comment by EmanDS** [comment]
I have installed again following the classical method on php 7.4 and php 8.0.2 still the same issue.
I am on production server CentOS 8, everything goes well but when at the end I go to the url of the installation (https://emmanuel-dossantos.fr/benotes/public/) I am getting a blank page.
My php settings https://emmanuel-dossantos.fr/benotes/info.php.
I could not find any log reporting an issue.
Thanks

**Comment by EmanDS** [comment]
What I can see that is wrong from the source code of the index page are the links starting with "/" like href="/manifest.json" which should be  href="benotes/public/manifest.json". But I do not know where to fix this...
<!doctype html>
--
  | <html lang="en" class="h-full">
  | <head>
  | <meta charset="utf-8">
  | <meta http-equiv="X-UA-Compatible" content="IE=edge">
  | <meta name="viewport" content="width=device-width, initial-scale=1">
  | <title>Benotes</title>
  | <link href="https://rsms.me/inter/inter.css" rel="stylesheet">
  | <link href="/css/app.css" type="text/css" rel="stylesheet">
  | <link rel="shortcut icon" type="image/png" href="/logo_144x144.png"/>
  | <link rel="manifest" href="/manifest.json">
  | </head>
  | <body class="h-full">
  | <div id="app" class="h-full">
  | <div class="w-full mx-auto h-full">
  | <router-view></router-view>
  | </div>
  | </div>
  | <script src="/js/app.js"></script>
  | </body>
  | </html>

<!doctype html>
<html lang="en" class="h-full">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Benotes</title>
        <link href="https://rsms.me/inter/inter.css" rel="stylesheet">
        <link href="[/css/app.css](https://emmanuel-dossantos.fr/css/app.css)" type="text/css" rel="stylesheet">
        <link rel="shortcut icon" type="image/png" href="[/logo_144x144.png](https://emmanuel-dossantos.fr/logo_144x144.png)"/>
        <link rel="manifest" href="[/manifest.json](https://emmanuel-dossantos.fr/manifest.json)">
    </head>
    <body class="h-full">
        <div id="app" class="h-full">
            <div class="w-full mx-auto h-full">
                <router-view></router-view>
            </div>
        </div>
        <script src="[/js/app.js](https://emmanuel-dossantos.fr/js/app.js)"></script>
    </body>
</html>

**Comment by fr0tt** [comment]
First of all, I'm pretty sure (but can't promise it right now) that `composer install` should complain when you try to install it with php8.
Do you use the same php version for php-cli ? 
Try to use for both of them php7.4 (You can still use newer php versions for other projects side by side.) 

Regarding your blank page problem you're probably right that the cause of it is the (relative) root path. This is a common issue. 
Usually you would use for every project a domain or subdomain instead of a subdirectory, but it's possible.
In order to help you I need to know which webserver are you using ? Apache or Nginx or ... ?

**Comment by EmanDS** [comment]
No complaints at all when installing with php8 but I can use php 7.4 as well.
My server is running apache

**Comment by EmanDS** [comment]
If I install it in the root path of the server instead of /subdirectory it works like a charm even with php 8. But I would like to use it in a /subdirectory...

**Comment by fr0tt** [comment]
I'm still surprised that php-cli8.0 works but all the better.

I thought about it and it might not be possible at the moment to make it work in a subdirectory. (Like I said, I can't test it myself this week.)

You can redirect with Apache /benotes/public to /benotes, but that won't solve the problem really.

Don't you have the option to use a subdomain ? (Or you could use an alternative port.)

**Comment by EmanDS** [comment]
Thanks for you answer.

Yes I will go with subdomain then.
Thanks a lot for your time.
Good work by the way.

Have a nice weekend.
Emmanuel

Envoyé de mon iPhone

Le 13 août 2022 à 10:41, fr0tt ***@***.***> a écrit :

﻿

I'm still surprised that php-cli8.0 works but all the better.

I thought about it and it might not be possible at the moment to make it work in a subdirectory. (Like I said, I can't test it myself this week.)

You can redirect with Apache /benotes/public to /benotes, but that won't solve the problem really.

Don't you have the option to use a subdomain ? (Or you could use an alternative port.)

**Comment by fr0tt** [comment]
Thank you very much !

I'm sorry that I wasn't able to help you making it work in a subdirectory.

Have a nice weekend aswell :)

**Comment by EmanDS** [comment]
it is already very kind of you to have spent time answering my questions. I appreciate.

I finally installed it at the root domain.


In fact your app is very complementary to my project (where I uploade PDFs & Excel files). I was wanting to merge both either by encapsulating mine into yours or the other way round but it looks more difficult as expected. I have not yet figured out how to do it as your app seems to have one main view served by a javascript file. But I will try to understand how it works and do it...


Thanks again.

Emmanuel

________________________________
De : fr0tt ***@***.***>
Envoyé : dimanche 14 août 2022 11:52:49
À : fr0tt/benotes
Cc : Emmanuel Dos Santos; Author
Objet : Re: [fr0tt/benotes] Blank page after installation (Issue #37)


Thank you very much !

I'm sorry that I wasn't able to help you making it work in a subdirectory.

Have a nice weekend aswell :)

**Comment by fr0tt** [comment]
That is very nice to say from you.

I am sometimes thinking about adding files aswell but I would probably have to change the "create" design in order to support different types without being to confusing or hidden.

The application is basically split into an SPA (single-page-application) as frontend and a backend that can communicate via a Rest Api with the former.

Perhaps one solution for you might be to include that [Rest Api](https://github.com/fr0tt/benotes/blob/master/api.md) in your own application.

**Comment by EmanDS** [comment]
Thanks for your message.

Good idea to include that Rest Api in my application.

I am going to test that.

Best regards
Emmanuel

Envoyé de mon iPhone

Le 15 août 2022 à 01:47, fr0tt ***@***.***> a écrit :

﻿

That is very nice to say from you.

I am sometimes thinking about adding files aswell but I would probably have to change the "create" design in order to support different types without being to confusing or hidden.

The application is basically split into an SPA (single-page-application) as frontend and a backend that can communicate via a Rest Api with the former.

Perhaps one solution for you might be to include that Rest Api<https://github.com/fr0tt/benotes/blob/master/api.md> in your own application.

**Comment by EmanDS** [comment]
Hello,

Sorry to annoye you once more.

I am trying to add a link to my other app on the Sidebar.vue but nothing happens.
Even if I delete all files and folders (except for views folder) in the resources folder your app continues to work as a charm.
Therefore, I do not know how to apply the change I want to make.

Could you advise?

Best regards,
Emmanuel

De : Emmanuel Dos Santos Santos ***@***.***>
Date : lundi 15 août 2022 à 09:58
À : fr0tt/benotes ***@***.***>
Cc : fr0tt/benotes ***@***.***>, Author ***@***.***>
Objet : Re: [fr0tt/benotes] Blank page after installation (Issue #37)

Thanks for your message.

Good idea to include that Rest Api in my application.

I am going to test that.

Best regards
Emmanuel
Envoyé de mon iPhone


Le 15 août 2022 à 01:47, fr0tt ***@***.***> a écrit :

That is very nice to say from you.

I am sometimes thinking about adding files aswell but I would probably have to change the "create" design in order to support different types without being to confusing or hidden.

The application is basically split into an SPA (single-page-application) as frontend and a backend that can communicate via a Rest Api with the former.

Perhaps one solution for you might be to include that Rest Api<https://github.com/fr0tt/benotes/blob/master/api.md> in your own application.

**Comment by fr0tt** [comment]
Hi again,

no need to apologize, I should have included instructions for development anyways.

No matter what you do with the entire resources/js folder there won't be any changes made unless you rebuild the SPA part of the application, which refreshes the famous (public)/js/app.js

In order to apply any changes you need to:

- install nodejs and npm - if you haven't
- `npm install` (install javascript dependencies)
- `npm run prod` (to build the frontend) or `npm run watch` (to build the frontend on the fly while you make changes)

**Comment by RomualdYT** [comment]
Hello, I do have the same problem on a subdomain. Same errors, same tries with 7.4 (CLI too)
Any ideas ? :(

**Comment by fr0tt** [comment]
Then I'm going to answer you on Reddit
